// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    BatchUpdateEntryRequest,
    HostsEntryDTO,
    HostsGroupDTO,
    HostsVersionDTO,
    PlatformInfoDTO
} from "./models.js";
