// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BatchUpdateEntryRequest 批量更新条目单项
 */
export class BatchUpdateEntryRequest {
    /**
     * Creates a new BatchUpdateEntryRequest instance.
     * @param {Partial<BatchUpdateEntryRequest>} [$$source = {}] - The source object to create the BatchUpdateEntryRequest.
     */
    constructor($$source = {}) {
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("comment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchUpdateEntryRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BatchUpdateEntryRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BatchUpdateEntryRequest(/** @type {Partial<BatchUpdateEntryRequest>} */($$parsedSource));
    }
}

/**
 * HostsEntryDTO hosts 条目数据传输对象
 */
export class HostsEntryDTO {
    /**
     * Creates a new HostsEntryDTO instance.
     * @param {Partial<HostsEntryDTO>} [$$source = {}] - The source object to create the HostsEntryDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("comment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostsEntryDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HostsEntryDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostsEntryDTO(/** @type {Partial<HostsEntryDTO>} */($$parsedSource));
    }
}

/**
 * HostsGroupDTO hosts 分组数据传输对象
 * 单一职责: 跨层数据传输，避免直接传递领域实体
 * DDD: DTO 用于隔离领域模型与外部接口
 */
export class HostsGroupDTO {
    /**
     * Creates a new HostsGroupDTO instance.
     * @param {Partial<HostsGroupDTO>} [$$source = {}] - The source object to create the HostsGroupDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("is_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_enabled"] = false;
        }
        if (!("order" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["order"] = 0;
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {HostsEntryDTO[]}
             */
            this["entries"] = [];
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostsGroupDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HostsGroupDTO}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField5_0($$parsedSource["entries"]);
        }
        return new HostsGroupDTO(/** @type {Partial<HostsGroupDTO>} */($$parsedSource));
    }
}

/**
 * HostsVersionDTO 版本历史数据传输对象
 */
export class HostsVersionDTO {
    /**
     * Creates a new HostsVersionDTO instance.
     * @param {Partial<HostsVersionDTO>} [$$source = {}] - The source object to create the HostsVersionDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("age" in $$source)) {
            /**
             * 版本年龄（天数）
             * @member
             * @type {number}
             */
            this["age"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostsVersionDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HostsVersionDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostsVersionDTO(/** @type {Partial<HostsVersionDTO>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = HostsEntryDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
