package service

import (
	"strings"
	"testing"

	"github.com/chen/wails3-hosts/internal/domain/entity"
)

// TestGenerateHostsContent 测试 hosts 内容生成
func TestGenerateHostsContent(t *testing.T) {
	service := NewHostsDomainService()

	// 创建测试分组
	group1 := entity.NewHostsGroup("开发环境", "本地开发服务器配置")
	group1.SetEnabled(true)
	group1.SetOrder(0)
	entry1 := entity.NewHostsEntry("127.0.0.1", "local.dev", "本地开发")
	entry1.Enabled = true
	group1.AddEntry(*entry1)

	group2 := entity.NewHostsGroup("测试环境", "测试服务器配置")
	group2.SetEnabled(true)
	group2.SetOrder(1)
	entry2 := entity.NewHostsEntry("192.168.1.100", "test.server", "测试服务器")
	entry2.Enabled = true
	group2.AddEntry(*entry2)

	group3 := entity.NewHostsGroup("未启用分组", "这个分组不应该出现")
	group3.SetEnabled(false) // 未启用

	groups := []*entity.HostsGroup{group1, group2, group3}

	// 生成 hosts 内容
	content := service.GenerateHostsContent(groups)

	// 验证内容
	t.Run("验证文件头", func(t *testing.T) {
		if !strings.Contains(content, "# Generated by Hosts Manager") {
			t.Error("缺少文件头标识")
		}
		if !strings.Contains(content, "# Total Groups: 3") {
			t.Error("分组总数不正确")
		}
	})

	t.Run("验证分组开始标记", func(t *testing.T) {
		if !strings.Contains(content, "# ===== 开始分组: 开发环境 =====") {
			t.Error("缺少分组1的开始标记")
		}
		if !strings.Contains(content, "# ===== 开始分组: 测试环境 =====") {
			t.Error("缺少分组2的开始标记")
		}
	})

	t.Run("验证分组结束标记", func(t *testing.T) {
		if !strings.Contains(content, "# ===== 结束分组: 开发环境 =====") {
			t.Error("缺少分组1的结束标记")
		}
		if !strings.Contains(content, "# ===== 结束分组: 测试环境 =====") {
			t.Error("缺少分组2的结束标记")
		}
	})

	t.Run("验证分组描述", func(t *testing.T) {
		if !strings.Contains(content, "# 描述: 本地开发服务器配置") {
			t.Error("缺少分组1的描述")
		}
		if !strings.Contains(content, "# 描述: 测试服务器配置") {
			t.Error("缺少分组2的描述")
		}
	})

	t.Run("验证分组ID", func(t *testing.T) {
		if !strings.Contains(content, "# 分组ID: ") {
			t.Error("缺少分组ID")
		}
	})

	t.Run("验证分隔线", func(t *testing.T) {
		if !strings.Contains(content, "# --------------------------------------") {
			t.Error("缺少分隔线")
		}
	})

	t.Run("验证hosts条目", func(t *testing.T) {
		if !strings.Contains(content, "127.0.0.1\tlocal.dev") {
			t.Error("缺少hosts条目1")
		}
		if !strings.Contains(content, "192.168.1.100\ttest.server") {
			t.Error("缺少hosts条目2")
		}
	})

	t.Run("验证未启用分组不出现", func(t *testing.T) {
		if strings.Contains(content, "未启用分组") {
			t.Error("未启用的分组不应该出现在生成的hosts文件中")
		}
	})

	t.Logf("生成的 hosts 内容:\n%s", content)
}

// TestGenerateHostsContentEmptyGroups 测试空分组情况
func TestGenerateHostsContentEmptyGroups(t *testing.T) {
	service := NewHostsDomainService()

	// 创建启用的空分组
	group1 := entity.NewHostsGroup("空分组", "没有任何条目")
	group1.SetEnabled(true)

	// 创建有内容的分组
	group2 := entity.NewHostsGroup("有效分组", "有内容")
	group2.SetEnabled(true)
	entry := entity.NewHostsEntry("127.0.0.1", "test.local", "测试")
	entry.Enabled = true
	group2.AddEntry(*entry)

	groups := []*entity.HostsGroup{group1, group2}

	content := service.GenerateHostsContent(groups)

	// 空分组不应该出现
	if strings.Contains(content, "空分组") {
		t.Error("空分组不应该出现在hosts文件中")
	}

	// 有效分组应该出现
	if !strings.Contains(content, "有效分组") {
		t.Error("有效分组应该出现")
	}

	t.Logf("生成的 hosts 内容:\n%s", content)
}
