package service

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/chen/wails3-demo/internal/domain/entity"
)

// HostsDomainService hosts 领域服务
// 单一职责: 处理涉及多个实体或复杂逻辑的领域操作
// DDD: 领域服务包含不属于某个特定实体的业务逻辑
type HostsDomainService struct{}

// NewHostsDomainService 创建领域服务实例
func NewHostsDomainService() *HostsDomainService {
	return &HostsDomainService{}
}

// GenerateHostsContent 生成最终的 hosts 文件内容
// 单一职责: 将多个分组合并为标准的 hosts 文件格式
func (s *HostsDomainService) GenerateHostsContent(groups []*entity.HostsGroup) string {
	var buffer bytes.Buffer

	// 添加文件头
	buffer.WriteString("# ======================================\n")
	buffer.WriteString("# Generated by Hosts Manager\n")
	buffer.WriteString(fmt.Sprintf("# Total Groups: %d\n", len(groups)))
	buffer.WriteString("# ======================================\n\n")

	// 遍历所有启用的分组
	for _, group := range groups {
		entries := group.GetEnabledEntries()
		if len(entries) == 0 {
			continue
		}

		// 添加分组注释
		buffer.WriteString(fmt.Sprintf("# Group: %s\n", group.Name))
		if group.Description != "" {
			buffer.WriteString(fmt.Sprintf("# %s\n", group.Description))
		}

		// 添加条目
		for _, entry := range entries {
			line := entry.ToHostsLine()
			if line != "" {
				buffer.WriteString(line + "\n")
			}
		}
		buffer.WriteString("\n")
	}

	return buffer.String()
}

// ValidateIP 验证 IP 地址格式
// 单一职责: IP 地址验证逻辑
func (s *HostsDomainService) ValidateIP(ip string) error {
	if ip == "" {
		return entity.ErrInvalidIP
	}

	// 基本验证: 必须包含点号（IPv4）或冒号（IPv6）
	if !strings.Contains(ip, ".") && !strings.Contains(ip, ":") {
		return entity.ErrInvalidIP
	}

	return nil
}

// ValidateHostname 验证主机名格式
// 单一职责: 主机名验证逻辑
func (s *HostsDomainService) ValidateHostname(hostname string) error {
	if hostname == "" {
		return entity.ErrInvalidHostname
	}

	// 长度检查
	if len(hostname) > 253 {
		return entity.ErrInvalidHostname
	}

	return nil
}

// DetectConflicts 检测分组中的冲突
// 单一职责: 检测同一主机名的多个映射
// 返回: map[hostname][]ip - 冲突的主机名及其对应的 IP 列表
func (s *HostsDomainService) DetectConflicts(groups []*entity.HostsGroup) map[string][]string {
	hostnameMap := make(map[string][]string)
	conflicts := make(map[string][]string)

	// 收集所有启用的主机名映射
	for _, group := range groups {
		if !group.IsEnabled {
			continue
		}

		for _, entry := range group.GetEnabledEntries() {
			hostnameMap[entry.Hostname] = append(hostnameMap[entry.Hostname], entry.IP)
		}
	}

	// 检测冲突（一个主机名对应多个 IP）
	for hostname, ips := range hostnameMap {
		if len(ips) > 1 {
			// 去重
			uniqueIPs := make(map[string]bool)
			for _, ip := range ips {
				uniqueIPs[ip] = true
			}

			if len(uniqueIPs) > 1 {
				conflictList := make([]string, 0, len(uniqueIPs))
				for ip := range uniqueIPs {
					conflictList = append(conflictList, ip)
				}
				conflicts[hostname] = conflictList
			}
		}
	}

	return conflicts
}

// MergeGroups 合并多个分组的内容（用于预览）
// DRY: 复用 GenerateHostsContent 的逻辑
func (s *HostsDomainService) MergeGroups(groups []*entity.HostsGroup) string {
	return s.GenerateHostsContent(groups)
}
