// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HostsHandler hosts 管理 Wails 服务处理器
 * 单一职责: 将应用服务暴露给 Wails 前端
 * DDD: 接口层负责外部接口适配，不包含业务逻辑
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../../application/dto/models.js";

/**
 * AddEntry 添加 hosts 条目
 * @param {string} groupID
 * @param {string} ip
 * @param {string} hostname
 * @param {string} comment
 * @returns {$CancellablePromise<void>}
 */
export function AddEntry(groupID, ip, hostname, comment) {
    return $Call.ByID(2592771619, groupID, ip, hostname, comment);
}

/**
 * ApplyHosts 应用 hosts 配置到系统
 * @param {string} sudoPassword
 * @returns {$CancellablePromise<void>}
 */
export function ApplyHosts(sudoPassword) {
    return $Call.ByID(3146797025, sudoPassword);
}

/**
 * BatchUpdateEntries 批量更新分组中的所有条目
 * @param {string} groupID
 * @param {dto$0.BatchUpdateEntryRequest[]} entries
 * @returns {$CancellablePromise<void>}
 */
export function BatchUpdateEntries(groupID, entries) {
    return $Call.ByID(927117481, groupID, entries);
}

/**
 * CreateGroup 创建新的 hosts 分组
 * @param {string} name
 * @param {string} description
 * @returns {$CancellablePromise<dto$0.HostsGroupDTO | null>}
 */
export function CreateGroup(name, description) {
    return $Call.ByID(739654197, name, description).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteEntry 删除 hosts 条目
 * @param {string} groupID
 * @param {string} entryID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteEntry(groupID, entryID) {
    return $Call.ByID(3542956047, groupID, entryID);
}

/**
 * DeleteGroup 删除分组
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteGroup(id) {
    return $Call.ByID(817392280, id);
}

/**
 * DetectConflicts 检测配置冲突
 * @returns {$CancellablePromise<{ [_: string]: string[] }>}
 */
export function DetectConflicts() {
    return $Call.ByID(2012154560).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GeneratePreview 生成 hosts 配置预览
 * @returns {$CancellablePromise<string>}
 */
export function GeneratePreview() {
    return $Call.ByID(1305520819);
}

/**
 * GetAllGroups 获取所有分组
 * @returns {$CancellablePromise<dto$0.HostsGroupDTO[]>}
 */
export function GetAllGroups() {
    return $Call.ByID(611128889).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetGroupByID 根据 ID 获取分组
 * @param {string} id
 * @returns {$CancellablePromise<dto$0.HostsGroupDTO | null>}
 */
export function GetGroupByID(id) {
    return $Call.ByID(3605839625, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetVersions 获取版本历史
 * @param {number} limit
 * @returns {$CancellablePromise<dto$0.HostsVersionDTO[]>}
 */
export function GetVersions(limit) {
    return $Call.ByID(4170854695, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * IsSudoPasswordCached 检查 sudo 密码是否已缓存
 * @returns {$CancellablePromise<boolean>}
 */
export function IsSudoPasswordCached() {
    return $Call.ByID(633975440);
}

/**
 * ReorderGroups 重新排序分组
 * @param {string[]} groupIDs
 * @returns {$CancellablePromise<void>}
 */
export function ReorderGroups(groupIDs) {
    return $Call.ByID(856750197, groupIDs);
}

/**
 * RollbackToVersion 回滚到指定版本
 * @param {string} versionID
 * @param {string} sudoPassword
 * @returns {$CancellablePromise<void>}
 */
export function RollbackToVersion(versionID, sudoPassword) {
    return $Call.ByID(2277117429, versionID, sudoPassword);
}

/**
 * ToggleGroup 切换分组启用状态
 * @param {string} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function ToggleGroup(id, enabled) {
    return $Call.ByID(2240039681, id, enabled);
}

/**
 * UpdateEntry 更新 hosts 条目
 * @param {string} groupID
 * @param {string} entryID
 * @param {string} ip
 * @param {string} hostname
 * @param {string} comment
 * @returns {$CancellablePromise<void>}
 */
export function UpdateEntry(groupID, entryID, ip, hostname, comment) {
    return $Call.ByID(1271603097, groupID, entryID, ip, hostname, comment);
}

/**
 * UpdateGroup 更新分组
 * @param {string} id
 * @param {string} name
 * @param {string} description
 * @returns {$CancellablePromise<void>}
 */
export function UpdateGroup(id, name, description) {
    return $Call.ByID(1333379478, id, name, description);
}

/**
 * ValidateSudoPassword 验证 sudo 密码
 * @param {string} password
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function ValidateSudoPassword(password) {
    return $Call.ByID(2021522024, password);
}

// Private type creation functions
const $$createType0 = dto$0.HostsGroupDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = dto$0.HostsVersionDTO.createFrom;
const $$createType6 = $Create.Array($$createType5);
